/* Generated by Yosys 0.41+8 (git sha1 1a54e8d47, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "design1.v:1.1-7.10" *)
module design1(a, b, y);
  (* src = "design1.v:2.16-2.17" *)
  input a;
  wire a;
  (* src = "design1.v:3.16-3.17" *)
  input b;
  wire b;
  (* src = "design1.v:4.17-4.18" *)
  output y;
  wire y;
  assign y = a &(* src = "design1.v:6.16-6.21" *)  b;
endmodule

(* cells_not_processed =  1  *)
(* src = "design2.v:1.1-7.10" *)
module design2(a, b, y);
  (* src = "design2.v:2.16-2.17" *)
  input a;
  wire a;
  (* src = "design2.v:3.16-3.17" *)
  input b;
  wire b;
  (* src = "design2.v:4.17-4.18" *)
  output y;
  wire y;
  assign y = a &(* src = "design2.v:6.16-6.21" *)  b;
endmodule
